### ISSUE TITLE
Errors with the new Version 1.12.3

### ISSUE THREAD

**Issue by EntomologicalZivi** [BernhardWebstudio/DataShot_DesktopApp#33]
1. Einträge mit einem eingefügtem Attribut können nicht kopiert und eingefügt werden.

2. Wenn man einen Eintrag in einen Anderen hinein kopiert in dem zuvor schon etwas eingefügt wurde, gibt es Komplikationen bei folgenden Feldern: "Collectors" und "Specimen Parts". Die kopierten Informationen sind dann zwar richtig, jedoch gibt es eine Fehlermeldung, dass der Eintrag nicht gespeichert werden kann, weil es doppelte Eingaben in einem Feld gibt. Dies ist nur bei den Zwei genannten Feldern der Fall. Bei anderen Feldern wie "Collection" ist dies nicht der Fall. Dort werden die bestehenden Angaben korrekt überschrieben.
Bemerkung: "Collectors" und "Specimen Parts" sind beides Felder bei denen man nicht direkt Informationen einfügen kann, sondern zuerst ein neues Feld erstellen muss. "Numbers & more" ist auch so ein Feld, da tritt dieses Speicher- / überschreiben-Problem nicht auf.

3. Das wechseln zwischen Einträgen geht noch etwas länger.

4. Wenn man ein Attribut hinzugefügt hat, wird es nicht direkt angezeigt. Man muss erst den Eintrag neu öffnen, oder auf das scheinbar leere Attribut Feld clicken.

5. State/Provinces welche Falsch eingefügt werden, wenn man eine Georeference hinzufügt (faslch->richtig): Zurich->Zürich, Grisons->Graubünden, Tessin->Ticino, Wallis->Valais, (Kantone sollten in ihrer "Landessprache" beschriftet sein),           
 Occitania->Occitanie,

**Comment by EntomologicalZivi** [comment]
Zum Punkt 1. noch: "Save & Copy" funktioniert. Wenn man im nächsten Eintrag dann auf "Paste" drückt, passiert jedoch nichts.

**Comment by GenieTim** [comment]
Just to be sure: we are talking about 1.12.3, not 1.1.2.3 (as in the title of this issue), right?

1. Yes, there was an issue where the specimenPart cloned the specimenPartAttribute cloned the specimenPart ... leading to an infinite recursion, ending with an overflow of the stack. Should be fixed in c1510b6
2. I am not sure I can replicate this. Could you please tell me examplaric barcodes of specimen to copy from and to?
3. Changing specimen by the arrows, by the "Edit" button in the search results, or changing another way? When I do it on my device, unfortunately, with these two ways, it is faster than < 0.3s. It this too slow or is it slower for you? Possible network issues?
4. Clicking "ok" to close the attribute dialog updates the field too. Not sure about the actual impact of when it is not updated earlier. It might be fixed in e540683
5. MIt "Falsch eingefügt", you mean the auto-fill when entering Lat/Long based on the OpenStreetMap query? I guess this would have to be solved with a dictionary to automatically replace certain names with others. Would you mind creating a .csv (and a corresponding new issue here on GitHub for easier reference later, when more replacements need to be added) with your colleagues with all replacements that need to be done?

**Comment by EntomologicalZivi** [comment]
Yes, talkin bout 1.12.3. oops

1. Fixed. Thanks.
2. It's working now.. so i guess we'll leave it like this.. i would get back to you if it does not..
3. Sometimes it's near to 3.0 sec. We have 1Gb up and download.. Gotta be somethig different.
4. Fixed. Thanks
5. Yes. I think Michael might already have such a list. We'll discuss it with him.

**Comment by EntomologicalZivi** [comment]
Nope.. Problem 2. ist still not fixed.. This should help.


https://user-images.githubusercontent.com/78074173/106149364-757d9180-617a-11eb-8039-51459f372f86.mp4


Afterwords you have to close and reopen the Programm.
And when you open up de failed specimen entry again, there are two rows in the Specimen parts segment istead of one.

**Comment by GenieTim** [comment]
Thanks for this video. I think it also shows quite nice why it is faster on my device: it waits for the image to be loaded (which it does not on my device). I changed that to show the rest already before the image is loaded in c325ff4.

With these Specimen examples, I was able to get an error too (though another one, for some reason), so thanks for those too. The error I got was caused whenever a new collector was set with the same name as the overwritten one. I *might* have fixed that one in b7d9994.

> Afterwards you have to close and reopen the Programm.

That sounds like a bug where the imagecapture.log could help me triage — could you please send it to me (info@bernhard-webstudio.ch) after such an error happened?

**Comment by EntomologicalZivi** [comment]
Now we have problems again with the "Specimen Attributes". It is kinda random. Sometimes when you copy and paste a record/entry the "Specimen Attribute" ist filled in, but when you open up this record/entry again some time later, the "Specimen Attribute" is just gone. And sometimes it works just fine.
In individual cases it is different again. If you open the record/entry again, suddenly there are two rows at the "Specimen Parts" an in both "Specimen Attribuzes" is missing.

Example: ETHZ-ENT0201967 to ETHZ-ENT0202003

**Comment by EntomologicalZivi** [comment]
Yepp. In nearly every record/entry we did with "copy and paste" yesterday, the Attributes are missing.

**Comment by GenieTim** [comment]
> Yepp. In nearly every record/entry we did with "copy and paste" yesterday, the Attributes are missing.

Probably same issue as @ greeffm reports in #35. I cannot reproduce the problem anymore in the newest version, in https://github.com/BernhardWebstudio/DataShot_DesktopApp/releases/tag/untagged-DataShot-20210202-1224-beta-4e640abe78604c204f35e6dfdf6503a56f99e7f3

**Comment by EntomologicalZivi** [comment]
Its working. Thanks. I guess this issue can be closed.

**Comment by GenieTim** [comment]
So all the points are fixed except 4, which we continue in #34, thanks!
